#!/bin/sh -e

if [ ! -h src/github.com/mickep76/tf ]; then
	mkdir -p src/github.com/mickep76/tf
	ln -s ../../.. src/github.com/mickep76/tf
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go install github.com/mickep76/tf
