#[etcd]
#etcd_node = "etcd1"
#etcd_node = 5001

#[inputs.Example]
#type = "file"
#path = "examples/example.yaml"

#[inputs.Example2]
#type = "file"
#path = "examples/example2.toml"

#[inputs.Global]
#type = "etcd"
#etcd_dir = "/global"

#[inputs.Subnet]
#type = "etcd"
#etcd_dir = "/subnet"

#[inputs.Host]
#type = "etcd"
#etcd_dir = "/host/{{.host}}"

[inputs.Peekaboo]
type = "http"
format = "JSON"
http_url = "http://iseeyou:5050/status/json"

#[merge.Config]
#inputs = [ "Global", "Subnet" ]
