[inputs.Example]
type = "file"
path = "examples/example.yaml"

[inputs.Example2]
type = "file"
path = "examples/example2.toml"

[inputs.Global]
type = "etcd"
etcd_node = "etcd1"
etcd_port = 5001
etcd_dir = "/global"

[inputs.Subnet]
type = "etcd"
etcd_node = "etcd1"
etcd_port = 5001
etcd_dir = "/subnet"

[inputs.Host]
type = "etcd"
etcd_node = "etcd1"
etcd_port = 5001
etcd_dir = "/host/{{.Host}}"

[merge.Config]
inputs = [ "Global", "Subnet" ]
